### PR TITLE
[My Site Migration] Integration Extension Request Form to status site

### LINKED ISSUE #1263: feat : add missing features in Task Card Component
### Issue Description
Add new features in _Task Card component_ in [status-site](https://status.realdevsquad.com/mine) 

### Expected Behavior
Users should be able to access the below features from the _Task Card Component_ which are available in [my-site](https://my.realdevsquad.com/tasks) not in [status-site](https://status.realdevsquad.com/mine) 

Features to be added in [status-site](https://status.realdevsquad.com/mine):

-   Task Status Updation 
-   Task Progress Bar Updation
-   Extension Request

The above mentioned features should be shown only to the **owner** of the task.

image

### Current Behavior
 - Users are not able to update task status
 - Users are not able to update task progress
 - Users are not able to create/mange extension request
 
image

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Go to [status-site](https://status.realdevsquad.com/mine)
2. Check the _Task Card_

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by RishiChaubey31**
Date: 29-05-2025

Developer Name: Rishi Chaubey

---

## Issue Ticket Number

- closes #1263 
## Description

- This PR contains the extension request form component which we utilise while filling up the extension request details
- Here are the test concerning this PR #1356 

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

https://github.com/user-attachments/assets/125f0633-60ea-47d2-9113-0d7be2fbc6ce

image

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

Screenshot 2025-06-04 141503

Screenshot 2025-06-04 141520

Screenshot 2025-06-05 012631

Screenshot 2025-06-05 012752

</details>

### CODE REVIEW

File: src/components/ExtensionRequest/ExtensionRequestForm.tsx [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+
+        if (name === 'newEndsOn') {
+            const timestamp = new Date(value).getTime();
+            setFormData((prev) => ({ ...prev, [name]: timestamp }));
+
+            if (oldEndsOn && timestamp <= oldEndsOn) {
+                setEtaError(true);
+            } else {
+                setEtaError(false);
+            }
```
[the remark this answers is not in the document]
Comment (RishiChaubey31) [reply src/components/ExtensionRequest/ExtensionRequestForm.tsx:82]: but can old end can ever be null because every task has a deadline which will be the old ends on

File: src/components/ExtensionRequest/ExtensionStatusModal.tsx [hunk 2]
```diff
@@ -105,13 +108,49 @@ export function ExtensionStatusModal({
...
+            )[0];
+
+            const timestampMs =
+                latestRequest.newEndsOn < 1e12
+                    ? latestRequest.newEndsOn * 1000
+                    : latestRequest.newEndsOn;
+
+            setOldEndsOn(timestampMs);
+        } else if (isOpen) {
+            setOldEndsOn(new Date().getTime());
```
Comment (RishiChaubey31) [inline src/components/ExtensionRequest/ExtensionStatusModal.tsx:124]: have to make a fix here for old ETA to be correct when no ER

File: src/components/ExtensionRequest/ExtensionRequestForm.tsx [hunk 3]
```diff
@@ -0,0 +1,216 @@
...
+        try {
+            await createExtensionRequest({
+                assignee: assignee,
+                newEndsOn: Math.floor(formData.newEndsOn / 1000),
+                oldEndsOn: submissionOldEndsOn,
+                reason: formData.reason,
+                status: 'PENDING',
+                taskId,
+                title: formData.title,
+                dev: true,
```
Comment (Achintya-Chatterjee) [inline src/components/ExtensionRequest/ExtensionRequestForm.tsx:102]: In `handleSubmit`, `newEndsOn` is converted to seconds before sending to the API (`Math.floor(formData.newEndsOn / 1000)`). However, `oldEndsOn` (derived from the `oldEndsOn` prop) is sent as milliseconds. Convert `oldEndsOn` to seconds before sending it to the `createExtensionRequest` payload.
 
 something like this would work i think `oldEndsOn: Math.floor(resolvedOldEndsOnMs / 1000)`

File: src/components/ExtensionRequest/ExtensionRequestForm.tsx [hunk 4]
```diff
@@ -0,0 +1,216 @@
...
+            }).unwrap();
+
+            toast(SUCCESS, EXTENSION_REQUEST_SUCCESS_MESSAGE);
+            onClose();
+        } catch (error: any) {
```
Comment (Achintya-Chatterjee) [inline src/components/ExtensionRequest/ExtensionRequestForm.tsx:107]: use proper types

**Review by Achintya-Chatterjee — CHANGES_REQUESTED** [review]

File: src/components/ExtensionRequest/ExtensionRequestForm.tsx (hunk 4 above)
Comment (RishiChaubey31) [reply src/components/ExtensionRequest/ExtensionRequestForm.tsx]: done

File: src/components/ExtensionRequest/ExtensionRequestForm.tsx (hunk 3 above)
Comment (RishiChaubey31) [reply src/components/ExtensionRequest/ExtensionRequestForm.tsx]: done

File: src/app/services/tasksApi.ts [hunk 5]
```diff
@@ -114,6 +116,21 @@ export const tasksApi = api.injectEndpoints({
...
+            ExtensionRequestCreatePayload & { dev?: boolean }
+        >({
+            query: (payload) => ({
+                url: '/extension-requests',
+                method: 'POST',
+                params: { dev: payload.dev ?? true },
+                body: (() => {
+                    const { dev, ...requestPayload } = payload;
+                    return requestPayload;
+                })(),
```
Comment (shubhdevelop) [inline src/app/services/tasksApi.ts:130]: why we are having a function that's immediately being resolved to just `requestpayload`?

**Review by shubhdevelop — COMMENTED** [review]
Rest LGTM

File: src/components/ExtensionRequest/ExtensionStatusModal.tsx [hunk 6]
```diff
@@ -105,13 +110,57 @@ export function ExtensionStatusModal({
...
+            )[0];
+
+            const isApproved = latestRequest.status === 'APPROVED';
+            const endsOnTimestamp = isApproved
+                ? latestRequest.newEndsOn < 1e12
+                    ? latestRequest.newEndsOn * 1000
+                    : latestRequest.newEndsOn
+                : initialOldEndsOn
+                ? initialOldEndsOn.getTime()
+                : null;
```
[the remark this answers is not in the document]
Comment (RishiChaubey31) [reply src/components/ExtensionRequest/ExtensionStatusModal.tsx]: done

**Review by shubhdevelop — DISMISSED** [review]
LGTM

**Review by Achintya-Chatterjee — DISMISSED** [review]
My comments have been resolved, hence approving this PR.

**Review by iamitprakash — APPROVED** [review]
