### PR TITLE
Redirect After Successful Progress Submit

### LINKED ISSUE #1066: Properly Redirect After Submitting Progress Update
### Issue Description

Properly Redirect After Submitting Progress Update.

### Expected Behavior

Same progress update form is shown which can be confused with failed to update progress.

### Current Behavior

The user should be redirected after submitting progress update.

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Reproducibility

 - [x] This issue is reproducible
-  [ ] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

### PR DESCRIPTION
**Pull request by ajoykumardas12**
Closes #1066 
### Issue:
- #1066 

### Description:
After successful progress submit user is redirected to related task details page.

### Feature Flag:
- [ ] Yes
- [x] No

### Frontend Changes
- [x] Yes
- [ ] No

### Backend Changes
- [ ] Yes
- [x] No

### Dev Tested:
- [x] Yes
- [ ] No

Screenshot_8
Screenshot_6
Screenshot_7

### Images/video of the change:
Before:

https://github.com/Real-Dev-Squad/website-status/assets/87164140/879a7351-48e6-4d5d-b55f-3b16723c13de

After:

https://github.com/Real-Dev-Squad/website-status/assets/87164140/4eef25e1-4ef5-43fe-b1c5-2c166bf9b8f0

### CODE REVIEW

File: src/components/ProgressForm/ProgressForm.tsx [hunk 1]
```diff
@@ -70,26 +68,29 @@ const ProgressForm = ({ questions }: formProps) => {
...
+                    className={styles.button}
+                    onClick={(e) => handleSubmit(e)}
+                    disabled={!isButtonEnabled}
+                    type="submit"
+                    data-testid="submit"
+                >
+                    Submit
+                </button>
+            </form>
+            {isLoading && <Loader />}
```
Comment (satyam73) [inline src/components/ProgressForm/ProgressForm.tsx:92]: Why Loader is here?

Comment (ajoykumardas12) [reply src/components/ProgressForm/ProgressForm.tsx:92]: In previous implementation if we press submit the form contents would disappear in the loading state and re-appear when loading finished, which isn't a great UX (you can check the `before changes` video). Having the loader here will ensure the form stays when it's submitting progress.

Comment (satyam73) [reply src/components/ProgressForm/ProgressForm.tsx:92]: hmm getting you point, In my opinion the loader should be on button itself with being disabled state

Comment (ajoykumardas12) [reply src/components/ProgressForm/ProgressForm.tsx:92]: Sure! I'll do this implementation, thanks for the suggestion.

File: src/components/reusables/reusables.module.scss [hunk 2]
```diff
@@ -0,0 +1,21 @@
+$gray: #808080;
```
Comment (sahsisunny) [inline src/components/reusables/reusables.module.scss:1]: Do we have no global file for colors?

File: src/components/reusables/reusables.module.scss
Comment (sahsisunny) [inline src/components/reusables/reusables.module.scss:1]: If this file is reusable, then it should be in the style directory, correct?

File: src/components/reusables/reusables.module.scss (hunk 2 above)
Comment (ajoykumardas12) [reply src/components/reusables/reusables.module.scss:1]: Global file is there, not used throughout the project except only few cases(Which should be changed). 
I've imported this from variables now.

File: src/components/reusables/reusables.module.scss
Comment (ajoykumardas12) [reply src/components/reusables/reusables.module.scss:1]: This corresponds to styles for components under `reusables/` folder. 
I'm not sure if this should be under `styles/` because the styles aren't global. We are using `.mudule.scss`, applying the styles by importing as variables. 
I'm changing the file name to component specific, that'd be better for reducing confusion.

**Review by sahsisunny — APPROVED** [review]

**Review by anishpawaskar — APPROVED** [review]
LGTM
