### PR TITLE
Fix/progress bar fix

### LINKED ISSUE #287: Progressbar should show green if the task is 100%
currently the progress indicator shows yellow in some cases even when the task is done 100%, it should show green

Image for reference⬇️

image

### PR DESCRIPTION
**Pull request by YashJain24-chief**
Problem: Progress Bar not green even when completion status is 100%
Closes #287 

Before changes:
image

After changes:
image

### CODE REVIEW

File: src/components/tasks/card/index.tsx [hunk 1]
```diff
@@ -85,7 +85,7 @@ const Card: FC<Props> = ({
   
   function handleProgressColor(percentCompleted: number, startedOn: string, endsOn: string): string {
     const percentageofDays = getPercentageOfDays(startedOn, endsOn)
-    if(percentageofDays >= percentCompleted) {
+    if(percentCompleted == 100 && (percentageofDays >= percentCompleted || percentageofDays < 0)) {
```
Comment (rajat-mehra05) [inline src/components/tasks/card/index.tsx:88]: Can we use `===` operator here ?

**Review by rajat-mehra05 — COMMENTED** [review]
LGTM! 👍

File: src/components/tasks/card/index.tsx [hunk 2]
```diff
@@ -85,7 +85,7 @@ const Card: FC<Props> = ({
   
   function handleProgressColor(percentCompleted: number, startedOn: string, endsOn: string): string {
     const percentageofDays = getPercentageOfDays(startedOn, endsOn)
-    if(percentageofDays >= percentCompleted) {
+    if(percentCompleted === 100 && (percentageofDays >= percentCompleted || percentageofDays < 0)) {
```
Comment (vinayak-trivedi) [inline src/components/tasks/card/index.tsx:88]: Hey can you add this percentageofDays < 0 condition to all the other if statements which are defining the color

Comment (ankushdharkar) [inline src/components/tasks/card/index.tsx:88]: This condition looks to be incorrect. 

If I have a task for a total of 10 days, and it's the 5th day today, but I have completed 80% of the task, then the progress bar should be green.

**Review by ankushdharkar — CHANGES_REQUESTED** [review]

File: src/components/tasks/card/index.tsx (hunk 2 above)
Comment (YashJain24-chief) [reply src/components/tasks/card/index.tsx:88]: In my opinion, percentageofDays<50,percentageofDays<25 already handles it. Am I missing something?
image

Comment (vinayak-trivedi) [reply src/components/tasks/card/index.tsx:88]: So in that case the percentage of days is greater than the percentage completed so it will show green

Comment (ankushdharkar) [reply src/components/tasks/card/index.tsx:88]: @YashJain24-chief Please paste the link to the code, not a screenshot of the isolated code.

Comment (ankushdharkar) [inline src/components/tasks/card/index.tsx:88]: Nit: Also, for readability reasons, is `percentageofDays` the number of days left or the days that have passed? Could we update the variable name please?

`percentageofDaysLeft` or `percentageofDaysPassed`

Comment (vinayak-trivedi) [inline src/components/tasks/card/index.tsx:88]: when you refactor the code, please make sure that this condition also changes `percentageofDays >= percentCompleted || percentageofDays < 0` it will return true even if  `percentageofDays >= percentCompleted` returns false

Comment (YashJain24-chief) [reply src/components/tasks/card/index.tsx:88]: https://github.com/Real-Dev-Squad/website-status/blob/1b14c606288aaeef7e40f60af852b7684ba81f03/src/components/tasks/card/index.tsx#L88

Comment (ankushdharkar) [reply src/components/tasks/card/index.tsx:88]: ` percentCompleted === 100 && (percentageofDays >= percentCompleted || percentageofDays < 0)` will become falsy for `percentCompleted=70, but percentageofDays=50.

The task is going well, because it's 70% done and we still have more than half the time left. It should be green.

Comment (YashJain24-chief) [reply src/components/tasks/card/index.tsx]: done

Comment (YashJain24-chief) [reply src/components/tasks/card/index.tsx]: done

Comment (YashJain24-chief) [reply src/components/tasks/card/index.tsx]: updated the coditions. Do they make more sense now?

**Review by vinayak-trivedi — APPROVED** [review]
LGTM

File: src/components/tasks/card/index.tsx [hunk 3]
```diff
@@ -79,22 +79,23 @@ const Card: FC<Props> = ({
     const daysLeft = endDate.diff(new Date(), 'days')
 
     // It provides the percentage of days left
-    const percentageofDays = daysLeft/totalDays * 100
-    return percentageofDays
+    const percentageofDaysLeft = daysLeft/totalDays * 100
```
Comment (ankushdharkar) [inline src/components/tasks/card/index.tsx:82]: Not camel-cased correctly.

File: src/components/tasks/card/index.tsx [hunk 4]
```diff
@@ -79,22 +79,23 @@ const Card: FC<Props> = ({
...
+    return percentageofDaysLeft
   }
   
   function handleProgressColor(percentCompleted: number, startedOn: string, endsOn: string): string {
-    const percentageofDays = getPercentageOfDays(startedOn, endsOn)
-    if(percentageofDays >= percentCompleted) {
+    const percentageofDaysLeft = getPercentageOfDays(startedOn, endsOn)
```
Comment (ankushdharkar) [inline src/components/tasks/card/index.tsx:87]: Should we rename the function too?

**Review by ankushdharkar — CHANGES_REQUESTED** [review]

File: src/components/tasks/card/index.tsx (hunk 3 above)
Comment (YashJain24-chief) [reply src/components/tasks/card/index.tsx:82]: done

File: src/components/tasks/card/index.tsx (hunk 4 above)
Comment (YashJain24-chief) [reply src/components/tasks/card/index.tsx:87]: How about refactoring it to setProgressBarColor?

Comment (rajat-mehra05) [reply src/components/tasks/card/index.tsx:87]: 1. I think he meant `getPercentageOfDays` could be renamed to `getPercentageOfDaysLeft`. Not sure though.
2. `handleProgressColor` looks fine.

Comment (YashJain24-chief) [reply src/components/tasks/card/index.tsx:87]: Got it. Will refactor getPercentageOfDays to getPercentageOfDaysLeft.
