### PR TITLE
Fixes date picker alignment and date value not showing up while editing on task details page

### LINKED ISSUE #1252: Draft: Date picker wrong alignment behaviour in dates section (for superuser)
### Issue Description

Date picker field have misplace alignment issues on the task details section for super user.
### Expected Behavior

Super user should be able to edit the dates in place of where the date value is shown.
### Current Behavior

Date picker is coming on side of value instead of switching from value while editing.
### Screenshots

issue:
image

should behave like:
image

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by Ayushsanjdev**
Date: 15-09-2024

Developer Name: Ayush Sanj

---

## Issue Ticket Number

- Closes #1252 

## Description

1. Date picker alignment issue fixed.
2. Loader like `Saving...` updated after saving the task.
3. Moved States to relevant components.
4. Code refactor.
5. Update relevant test cases.

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

https://github.com/user-attachments/assets/f619ae91-2cc1-4367-9a22-adfa237335d6

with extension icon:

https://github.com/user-attachments/assets/849b6bd9-8b07-460b-90fb-5ab07a27ba90

with feature dev flag toggle:

https://github.com/user-attachments/assets/9b54fb07-e22b-4110-9b89-351a6411bf36

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

image

image

</details>

## Additional Notes

Found some states in parent component unnecessarily prop drilled which could have been used in details component. so refactored it. To show the input field, I put it in details component to be shown with isEditing + isUserAuthorised. Updated test cases for same. New addition: `Saving...` Loader to show on save while saving task.

### CODE REVIEW

**Review by iamitprakash — APPROVED** [review]

File: src/components/taskDetails/index.tsx [hunk 1]
```diff
@@ -63,8 +64,8 @@ type Props = {
 const TaskDetails: FC<Props> = ({ taskID }) => {
     const router = useRouter();
     const { isUserAuthorized } = useUserData();
-    const [newEndOnDate, setNewEndOnDate] = useState('');
     const [isEditing, setIsEditing] = useState<boolean>(false);
+    const [loading, setLoading] = useState<boolean>(false);
```
Comment (vinit717) [inline src/components/taskDetails/index.tsx:68]: Do we need this as RTK query give loading state?

File: __tests__/Unit/Components/Tasks/TaskDetails.test.tsx
Comment (vinit717) [inline __tests__/Unit/Components/Tasks/TaskDetails.test.tsx:1]: Use data test id

File: src/components/taskDetails/Details.tsx
Comment (vinit717) [inline src/components/taskDetails/Details.tsx:1]: write test for this file

File: src/components/taskDetails/TaskHeader.tsx
Comment (vinit717) [inline src/components/taskDetails/TaskHeader.tsx:1]: Test is missing for this

**Review by vinit717 — CHANGES_REQUESTED** [review]

File: __tests__/Unit/Components/Tasks/TaskDetails.test.tsx
Comment (Ayushsanjdev) [reply __tests__/Unit/Components/Tasks/TaskDetails.test.tsx:1]: I have used data-test-id in input.

File: src/components/taskDetails/Details.tsx
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx:1]: yes, working on it

File: src/components/taskDetails/TaskHeader.tsx
Comment (Ayushsanjdev) [reply src/components/taskDetails/TaskHeader.tsx:1]: yes, working on it

File: src/components/taskDetails/index.tsx (hunk 1 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/index.tsx:68]: No I tested, it does not show loading true when I save it, so for button I needed it separately, Please let me know if any misunderstanding.

**Review by Achintya-Chatterjee — COMMENTED** [review]
can you please upload a video, there should be extension link in the end date

**Comment by Ayushsanjdev** [comment]
> can you please upload a video, there should be extension link in the end date

Uploaded @Achintya-Chatterjee inside screenshot, please let me know any misunderstandings

**Comment by Ayushsanjdev** [comment]
@vinit717 updated changes that you asked, Please have a look, thanks!

File: src/components/taskDetails/Details.tsx [hunk 2]
```diff
@@ -68,34 +87,52 @@ const Details: FC<TaskDetailsProps> = ({ detailType, value, url }) => {
...
+                        >
+                            {tooltipActive
+                                ? formatDate(value)
+                                : getRelativeTime(value)}
+                        </Tooltip>
+                    ) : (
+                        renderedValue
+                    )}
+                </span>
+            )}
```
Comment (vinit717) [inline src/components/taskDetails/Details.tsx:135]: Why too much nesting?

Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx:135]: I know, actually I saw it being already there, do you want me to refactor in this PR only?

Comment (vinit717) [reply src/components/taskDetails/Details.tsx:135]: Then make your timedetails a component in same file

Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx:135]: okay

Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx]: updated

**Comment by Ayushsanjdev** [comment]
@vinit717 , refactored that nested code.

**Comment by Ayushsanjdev** [comment]
@vinit717 updated test screenshot:
* all test passed:
image

*coverage:
image

**Comment by vinit717** [comment]
> Reference in new issue
> Edit
> Hide
> Delete

Can you increase index file and taskdate file test coverage

**Comment by Ayushsanjdev** [comment]
> > Reference in new issue
> > Edit
> > Hide
> > Delete
> 
> Can you increase index file and taskdate file test coverage

Ok will work on it 👍

File: src/components/taskDetails/Details.tsx [hunk 3]
```diff
@@ -1,20 +1,86 @@
...
+    }, [isEditing]);
+
+    const handleBlurOfEndsOn = () => {
+        const endsOn = new Date(`${newEndOnDate}`).getTime() / 1000;
+
+        if (endsOn > 0) {
+            setEditedTaskDetails?.((prev) => ({
+                ...prev,
+                endsOn,
+            }));
```
Comment (Achintya-Chatterjee) [inline src/components/taskDetails/Details.tsx:81]: You are using `useEffect` to clear the `newEndOnDate` when `isEditing` changes. This is fine but can lead to unnecessary re-renders. You can optimize the `useEffect` hook by ensuring that the value of `isEditing` is actually changing before resetting the state. Alternatively, you could consider a different way to reset the form state that doesn’t rely on this side effect.

Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx]: But I have already added a check if isEditiing is false only then, what I additionally can add is to check if newEndOnDate is not null.

File: src/components/taskDetails/Details.tsx [hunk 4]
```diff
@@ -1,20 +1,86 @@
...
+    const { detailType, value, url, isEditing, setEditedTaskDetails } = props;
     const color = value ? setColor?.[value] : undefined;
     const isGitHubLink = detailType === 'Link';
     const gitHubIssueLink = isGitHubLink ? value : undefined;
+    const [newEndOnDate, setNewEndOnDate] = useState('');
+    const { isUserAuthorized } = useUserData();
+
+    useEffect(() => {
+        if (!isEditing && newEndOnDate !== '') setNewEndOnDate('');
+    }, [isEditing, newEndOnDate]);
```
Comment (Achintya-Chatterjee) [inline src/components/taskDetails/Details.tsx:72]: `useEffect` is triggered whenever either `isEditing` or `newEndOnDate` changes, but logically, you only need to reset the date when `isEditing` changes from `true` to `false`.


You can simplify this by using `useEffect` only for `isEditing`:
```suggestion
   useEffect(() => {
    if (!isEditing) setNewEndOnDate('');
}, [isEditing]);

```


This will avoid unnecessary updates and improve performance slightly by preventing the `setNewEndOnDate` function from being called on every render when the date changes.

File: src/components/taskDetails/Details.tsx [hunk 5]
```diff
@@ -1,20 +1,86 @@
...
+
+    const handleBlurOfEndsOn = () => {
+        const endsOn = new Date(`${newEndOnDate}`).getTime() / 1000;
```
Comment (Achintya-Chatterjee) [inline src/components/taskDetails/Details.tsx:75]: usage of `new Date()` can lead to unexpected results with invalid date formats, as `new Date()` will convert invalid dates to `NaN`. This will likely prevent proper error handling for invalid dates.

use a more robust date validation method (e.g., `Date.parse()` or a library like `date-fns`) to ensure that invalid dates are handled gracefully.

File: src/components/taskDetails/Details.tsx [hunk 6]
```diff
@@ -1,20 +1,86 @@
...
+        >
+            {isGitHubLink && value ? (
+                <a
+                    className={styles.gitLink}
+                    href={gitHubIssueLink}
+                    target="_blank"
+                    rel="noopener noreferrer"
+                    aria-label="Open GitHub Issue"
+                    title={value}
+                >
```
Comment (Achintya-Chatterjee) [inline src/components/taskDetails/Details.tsx:42]: In the `DetailsContent` component, you have null checks for optional props like `isGitHubLink`:


Since `isGitHubLink`, `isTimeDetail`, etc., are likely boolean props, there is no need to check for both `isGitHubLink` and value. The component can be simplified. If `value` is a required prop when `isGitHubLink` is true, streamline the checks to reduce redundancy.

**Review by Achintya-Chatterjee — COMMENTED** [review]
Also looks why tests are failing

File: src/components/taskDetails/Details.tsx (hunk 4 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx:72]: This is what I did previously

Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx:72]: https://github.com/Real-Dev-Squad/website-status/pull/1260#discussion_r1769262587

File: src/components/taskDetails/Details.tsx (hunk 5 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx:75]: Ok will check this

**Comment by Ayushsanjdev** [comment]
> Also looks why tests are failing

Can you please rerun it

File: src/components/taskDetails/Details.tsx (hunk 6 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx:42]: Ok will check

**Comment by Achintya-Chatterjee** [comment]
> > Also looks why tests are failing
> 
> Can you please rerun it

@Ayushsanjdev After re-running it, tests are still failing. the tests that are failing are written by you

**Comment by Ayushsanjdev** [comment]
> > > Also looks why tests are failing
> > 
> > 
> > Can you please rerun it
> 
> @Ayushsanjdev After re-running it, tests are still failing. the tests that are failing are written by you

Weird, I will check once more

File: src/components/taskDetails/Details.tsx (hunk 4 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx]: reverted and pushed changes this way

File: src/components/taskDetails/Details.tsx (hunk 5 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx]: fixed

File: src/components/taskDetails/Details.tsx (hunk 6 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx]: updated

**Comment by Ayushsanjdev** [comment]
image
@vinit717 updated test cases coverage ^

**Review by Achintya-Chatterjee — DISMISSED** [review]

File: src/components/taskDetails/Details.tsx [hunk 7]
```diff
@@ -1,20 +1,101 @@
...
     const isGitHubLink = detailType === 'Link';
     const gitHubIssueLink = isGitHubLink ? value : undefined;
+    const [newEndOnDate, setNewEndOnDate] = useState('');
+    const { isUserAuthorized } = useUserData();
+
+    useEffect(() => {
+        if (!isEditing) setNewEndOnDate('');
+    }, [isEditing]);
+
+    const isValidDate = (dateString: string) => {
```
Comment (vinit717) [inline src/components/taskDetails/Details.tsx:76]: can you move this in utils

File: src/components/taskDetails/Details.tsx [hunk 8]
```diff
@@ -1,20 +1,101 @@
...
+                    }}
+                >
+                    {tooltipActive ? formatDate(value) : getRelativeTime(value)}
+                </Tooltip>
+            ) : (
+                displayValue
+            )}
+        </span>
+    );
+};
```
Comment (vinit717) [inline src/components/taskDetails/Details.tsx:62]: Please refactor this nested condition

File: src/components/taskDetails/Details.tsx [hunk 9]
```diff
@@ -1,20 +1,101 @@
...
+
+    const isValidDate = (dateString: string) => {
+        // Validating the "YYYY-MM-DD" format strictly
+        const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
+        return (
+            dateRegex.test(dateString) && !isNaN(new Date(dateString).getTime())
+        );
+    };
+
+    const handleBlurOfEndsOn = () => {
```
Comment (vinit717) [inline src/components/taskDetails/Details.tsx:84]: Can you please change the function name

File: src/components/taskDetails/Details.tsx (hunk 7 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx]: done

File: src/components/taskDetails/Details.tsx (hunk 8 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx]: done

File: src/components/taskDetails/Details.tsx (hunk 9 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx]: done

File: src/components/taskDetails/Details.tsx [hunk 10]
```diff
@@ -1,20 +1,110 @@
...
+        return (
+            <span
+                className={styles.detailValue}
+                style={{ color: color ?? 'black' }}
+            >
+                <Tooltip
+                    content={formatDate(value)}
+                    tooltipPosition={{
+                        top: '-3.6rem',
+                        right: '-4.5rem',
```
Comment (vinit717) [inline src/components/taskDetails/Details.tsx:62]: Do we need negative value here?

**Comment by vinit717** [comment]
Can you please put this feature behind feature flag

File: src/components/taskDetails/Details.tsx (hunk 10 above)
Comment (Ayushsanjdev) [reply src/components/taskDetails/Details.tsx:62]: It was previously there and for tooltip position alignment it is required.

**Comment by Ayushsanjdev** [comment]
@vinit717 updated feature flag

**Review by Achintya-Chatterjee — DISMISSED** [review]

**Comment by vinit717** [comment]
Can you update the video for feature flag

**Comment by Ayushsanjdev** [comment]
@vinit717 updated feature flag video in screen shot section

File: __tests__/Unit/Components/Tasks/TaskDates.test.tsx [hunk 11]
```diff
@@ -1,28 +1,176 @@
...
+            </Provider>
         );
 
         const input = screen.getByTestId('endsOnTaskDetails');
         expect(input).toBeInTheDocument();
-        fireEvent.blur(input);
-        expect(mockHandleBlurOfEndsOn).toHaveBeenCalled();
+    });
+
+    it('should render correctly with non-admin role', () => {
```
[the remark this answers is not in the document]
Comment (Ayushsanjdev) [reply __tests__/Unit/Components/Tasks/TaskDates.test.tsx]: updated

**Review by vinit717 — APPROVED** [review]

**Review by asharma991 — APPROVED** [review]
LGTM

**Review by shubhdevelop — APPROVED** [review]
LGTM as well
