### PR TITLE
[FIX] - Progress Slider Feature

### LINKED ISSUE #720: [FIX] - Progress Slider Feature
### Issue

1. Fix CSS of Progress Text, add button clickable effect
2. Add Loader when the user stops sliding and the request to update progress is sent to the backend.

### LINKED ISSUE #722: Progress slider giving unauthorized message
Issue - 
1. on updating progress through the slider in production, it gives an error
   error: "Unauthorized"
  message: "You are not authorized for this action."
  statusCode: 401

2. on giving an error message Progress submitted successful message is showing

image

### PR DESCRIPTION
**Pull request by Pratiyushkumar**
### Description:
on updating progress through the slider in production, it gives an error
error: "Unauthorized"
message: "You are not authorized for this action."
statusCode: 401
Fix CSS of Progress Text, add button clickable effect
Add Loader when the user stops sliding and the request to update progress is sent to the backend.

### Dev Tested:
- [x] Yes
- [ ] No

### Test Coverage
image
image
image

### Images/video of the change:

https://github.com/Real-Dev-Squad/website-status/assets/82165483/f548eaa5-1b97-42ee-b982-46fd29522c38

image

### Follow up Issue -
https://github.com/Real-Dev-Squad/website-status/issues/780

### CODE REVIEW

File: src/components/tasks/card/index.tsx [hunk 1]
```diff
@@ -63,7 +66,9 @@ const Card: FC<Props> = ({
     const { data } = useGetUserQuery();
     const [progress, setProgress] = useState<boolean>(false);
     const [progressValue, setProgressValue] = useState<number>(0);
-    const [updateTasks] = useUpdateTaskMutation();
+    // const [updateTasks, { isLoading: isProgressLoading }] =
```
Comment (bharati-21) [inline src/components/tasks/card/index.tsx:69]: Please remove commented code

File: src/hooks/useAuthenticated.ts
Comment (sahsisunny) [inline src/hooks/useAuthenticated.ts:1]: Why did you delete this `src/hooks/useAuthenticated.ts` custom hook?

File: src/components/tasks/card/index.tsx [hunk 2]
```diff
@@ -308,11 +315,20 @@ const Card: FC<Props> = ({
...
+                id: id,
+            })
+                .unwrap()
+                .then(() => toast(SUCCESS, 'Progress Updated Successfully'))
+                .catch(() => toast(ERROR, 'Something Went wrong!'));
+        } else {
+            await updateSelfTask({ task: data, id: id })
+                .unwrap()
+                .then(() => toast(SUCCESS, 'Progress Updated Successfully'))
+                .catch(() => toast(ERROR, 'Something Went wrong!'));
```
Comment (sahsisunny) [inline src/components/tasks/card/index.tsx:330]: Can you move this error message to separate constants files?

File: src/hooks/useAuthenticated.ts
Comment (Pratiyushkumar) [reply src/hooks/useAuthenticated.ts:1]: actually this was visit's change that   was pushed by me by mistake so I deleted it

File: src/components/tasks/card/index.tsx (hunk 2 above)
Comment (Pratiyushkumar) [reply src/components/tasks/card/index.tsx:330]: fixed

File: src/components/tasks/card/index.tsx (hunk 1 above)
Comment (Pratiyushkumar) [reply src/components/tasks/card/index.tsx]: fixed

**Review by apurvkhare — DISMISSED** [review]
LGTM

File: src/app/services/tasksApi.ts [hunk 3]
```diff
@@ -48,6 +48,21 @@ export const tasksApi = api.injectEndpoints({
...
+                body: task.task,
+            }),
+            invalidatesTags: (_result, _err, { id }) => [
+                {
+                    type: 'Tasks',
+                    id,
+                },
+            ],
+        }),
+
```
Comment (vinit717) [inline src/app/services/tasksApi.ts:65]: please write test for this also

Comment (Pratiyushkumar) [reply src/app/services/tasksApi.ts:65]: done

**Review by bharati-21 — DISMISSED** [review]
LGTM

**Review by iamitprakash — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]

**Review by iamitprakash — CHANGES_REQUESTED** [review]

File: __mocks__/handlers/tasks.handler.js [hunk 4]
```diff
@@ -15,6 +15,11 @@ const taskHandlers = [
     rest.patch(`${URL}/tasks/:taskId`, (_, res, ctx) => {
         return res(ctx.delay(5000), ctx.status(204));
     }),
+
+    rest.patch(`${URL}/tasks/self/:taskId`, (_, res, ctx) => {
```
[the remark this answers is not in the document]
Comment (Pratiyushkumar) [reply __mocks__/handlers/tasks.handler.js:19]: delay removed

File: __mocks__/handlers/tasks.handler.js [hunk 5]
```diff
@@ -15,6 +15,11 @@ const taskHandlers = [
...
+        return res(ctx.delay(5000), ctx.status(204));
```
[the remark this answers is not in the document]
Comment (Pratiyushkumar) [reply __mocks__/handlers/tasks.handler.js]: delay removed

**Review by iamitprakash — APPROVED** [review]

**Review by iamitprakash — APPROVED** [review]

File: src/utils/getPercentageOfDaysLeft.ts [hunk 6]
```diff
@@ -1,13 +1,8 @@
...
-function inputParser(input: string) {
-    const parsedDate = moment(new Date(parseInt(input, 10) * 1000));
-    return parsedDate;
-}
-
 const getPercentageOfDaysLeft = (startedOn: string, endsOn: string): number => {
-    const startDate = inputParser(startedOn);
-    const endDate = inputParser(endsOn);
+    const startDate = moment(new Date(parseInt(startedOn, 10) * 1000));
+    const endDate = moment(new Date(parseInt(endsOn, 10) * 1000));
```
Comment (bharati-21) [inline src/utils/getPercentageOfDaysLeft.ts:5]: Why was inputParser removed here? The function could have been used to achieve the same - you wouldn't have had the need to repeat this: `moment(new Date(parseInt(_, 10) * 1000))`
The only difference is `_`. other than that it's the same code.

File: src/components/tasks/card/index.tsx [hunk 7]
```diff
@@ -456,6 +474,10 @@ const Card: FC<CardProps> = ({
                             progress={progress}
                             handleSaveProgressUpdate={handleSaveProgressUpdate}
                             handleProgressUpdate={handleProgressUpdate}
+                            loading={
+                                isLoadingUpdateTaskDetails ||
+                                isLoadingSelfTaskUpdate
+                            }
                         />
                     )}
                 </div>
```
Comment (bharati-21) [inline src/components/tasks/card/index.tsx:483]: As a future refactor, please move the progress bar code separately so that all local state and variables are only scoped to that specific component.

**Comment by bharati-21** [comment]
Once the user stops sliding the progress bar and the API call is initiated please disable changes to the slide until the update call is completed.

**Review by vinit717 — APPROVED** [review]

File: __tests__/Unit/Components/Tasks/ProgressText.test.tsx [hunk 8]
```diff
@@ -7,20 +7,30 @@ const DefaultProps = {
...
+                    progress={progress}
+                    loading={false}
+                    {...DefaultProps}
+                />
+            </>
         );
-        fireEvent.click(screen.getByText('save Progress'));
-        expect(getByText('save Progress')).toBeInTheDocument();
+        fireEvent.click(screen.getByText('SAVE'));
+        expect(getByText('SAVE')).toBeInTheDocument();
```
Comment (ankushdharkar) [inline __tests__/Unit/Components/Tasks/ProgressText.test.tsx:22]: What are we checking here?

Should the `Save` not disappear after clicking it, and change to `Update` for the same user?

File: __tests__/Unit/Components/Tasks/ProgressText.test.tsx [hunk 9]
```diff
@@ -7,20 +7,30 @@ const DefaultProps = {
...
+            <HandleProgressText
+                progress={progress}
+                loading={false}
+                {...DefaultProps}
+            />
         );
-        fireEvent.click(screen.getByText('Progress update'));
-        expect(getByText('Progress update')).toBeInTheDocument();
+        fireEvent.click(screen.getByText('UPDATE'));
+        expect(getByText('UPDATE')).toBeInTheDocument();
```
Comment (ankushdharkar) [inline __tests__/Unit/Components/Tasks/ProgressText.test.tsx:34]: Re: Should `Update` not change to `Save`?

File: src/components/tasks/card/ProgressSlider.tsx [hunk 10]
```diff
@@ -16,6 +17,7 @@ const ProgressSlider: FC<ProgressSliderProps> = ({
             step="10"
             onChange={(e) => handleProgressChange(e)}
             onMouseUp={() => debounceSlider(1000)}
+            disabled={loading ? true : false}
```
Comment (ankushdharkar) [inline src/components/tasks/card/ProgressSlider.tsx:20]: Nit:
```suggestion
            disabled={loading}
```

File: src/components/tasks/card/ProgressSlider.tsx [hunk 11]
```diff
@@ -6,6 +6,7 @@ const ProgressSlider: FC<ProgressSliderProps> = ({
     value,
     debounceSlider,
     handleProgressChange,
+    loading,
```
Comment (ankushdharkar) [inline src/components/tasks/card/ProgressSlider.tsx:9]: Nit: Can this be `isLoading`?

File: src/components/tasks/card/ProgressText.tsx [hunk 12]
```diff
@@ -1,19 +1,24 @@
...
 
 const HandleProgressText: FC<handleProgressTextProps> = ({
     progress,
     handleSaveProgressUpdate,
     handleProgressUpdate,
+    loading,
 }) => {
+    if (loading) {
+        return <Loader />;
+    }
```
Comment (ankushdharkar) [inline src/components/tasks/card/ProgressText.tsx:14]: Re: isLoading?

**Review by ankushdharkar — CHANGES_REQUESTED** [review]
Please fix the test cases and also put the mobile screenshots/recording

**Review by sahsisunny — APPROVED** [review]

File: __tests__/Unit/hooks/tasksApi.test.tsx [hunk 13]
```diff
@@ -357,6 +359,70 @@ describe('useUpdateTaskMutation()', () => {
...
+        expect(loadingResponse.isLoading).toBe(true);
+
+        await waitForNextUpdate({ timeout: 7000 });
+
+        const nextResponse = result.current[1];
+        expect(nextResponse.data).toBeNull();
+        expect(nextResponse.isSuccess).toBe(true);
+        expect(nextResponse.isLoading).toBe(false);
+        expect(nextResponse.status).toBe(QueryStatus.fulfilled);
+    }, 7000);
```
Comment (RitikJaiswal75) [inline __tests__/Unit/hooks/tasksApi.test.tsx:396]: can we check for status 204 here?

File: src/components/tasks/card/index.tsx
Comment (RitikJaiswal75) [inline src/components/tasks/card/index.tsx:1]: rather than modifying the task card component to always show this lets change it to be available based on an optional prop passes, which will be passed to card from src/pages/mine/index.tsx

**Review by RitikJaiswal75 — CHANGES_REQUESTED** [review]

**Comment by iamitprakash** [comment]
Please mention all PR related details like DB changes and all....

File: src/components/tasks/card/index.tsx [hunk 14]
```diff
@@ -313,11 +323,20 @@ const Card: FC<CardProps> = ({
         const data = {
             percentCompleted: percentCompleted,
         };
-        await updateTasks({
-            task: data,
-            id: id,
-        });
-        toast(SUCCESS, 'Progress Updated Successfully');
+        if (isUserAuthorized) {
+            await updateTask({
```
Comment (TanishqSingla) [inline src/components/tasks/card/index.tsx:327]: here we're using await, but at the same time `.then()` is also being used

File: src/components/tasks/card/index.tsx [hunk 15]
```diff
@@ -313,11 +323,20 @@ const Card: FC<CardProps> = ({
...
+                task: data,
+                id: id,
+            })
+                .unwrap()
+                .then(() => toast(SUCCESS, PROGRESS_SUCCESSFUL))
+                .catch(() => toast(ERROR, ERROR_MESSAGE));
+        } else {
+            await updateSelfTask({ task: data, id: id })
```
Comment (TanishqSingla) [inline src/components/tasks/card/index.tsx:335]: same as above

File: src/constants/constants.ts [hunk 16]
```diff
@@ -5,4 +5,5 @@ export const COMPLETED = 'COMPLETED';
 export const DONE = 'DONE';
 export const AVAILABLE = 'AVAILABLE';
 export const UNASSINGED = 'UNASSINGED';
+export const PROGRESS_SUCCESSFUL = 'Progress Updated Successfully';
```
Comment (TanishqSingla) [inline src/constants/constants.ts:8]: NIT: we can create this message inside an object, this will create a separate context for messages related to PROGRESS and we can add more messages inside this object.
Feel free to ignore this suggestion if this is not under the scope of change.

```suggestion
export const PROGRESS_MESSAGE = {
  UPDATE_SUCCESS = 'Progress Updated Successfully'
};
```

**Review by TanishqSingla — CHANGES_REQUESTED** [review]
good job with the PR, have added some comments do check them out

File: src/components/tasks/card/index.tsx (hunk 15 above)
Comment (Pratiyushkumar) [reply src/components/tasks/card/index.tsx:335]: image

reference - https://redux-toolkit.js.org/rtk-query/usage/error-handling

This is used to handle RTK success and error status, please see the reference I have shared

File: src/components/tasks/card/index.tsx (hunk 14 above)
Comment (Pratiyushkumar) [reply src/components/tasks/card/index.tsx:327]: below is the reason mentioned

File: src/components/tasks/card/index.tsx (hunk 15 above)
Comment (TanishqSingla) [reply src/components/tasks/card/index.tsx:335]: The example you mentioned doesn't use `await` as it is using `.then()` `.catch()` to handle the promise's result. In your case you're using both, `await` and `.then()` `.catch()`

File: __tests__/Unit/hooks/tasksApi.test.tsx (hunk 13 above)
Comment (RitikJaiswal75) [reply __tests__/Unit/hooks/tasksApi.test.tsx:396]: even status of 200 will give a fulfilled status we need to

File: src/components/tasks/card/index.tsx
Comment (RitikJaiswal75) [reply src/components/tasks/card/index.tsx:1]: I was thinking of passing the update progress component as props. so that the component is extracted and code is clean. we can render the component based on some condition then.

Comment (Pratiyushkumar) [reply src/components/tasks/card/index.tsx:1]: This is part of refactoring and will have to think about this if this can be done or not but in this PR I am not going to do such a thing because there is already a delay due to the PR review, refactoring already ticket is created
https://github.com/Real-Dev-Squad/website-status/issues/687
had a discussion with Bhavika that when this PR gets merged I will work on the 687.

File: __tests__/Unit/hooks/tasksApi.test.tsx (hunk 13 above)
Comment (Pratiyushkumar) [reply __tests__/Unit/hooks/tasksApi.test.tsx:396]: but with the handler returning 204 on success then why should we consider for 200 status code?

**Review by sahsisunny — APPROVED** [review]

**Review by iamitprakash — APPROVED** [review]
